import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import {
  createContactCommand,
  updateContactCommand,
} from '../../lib/security/domains/contacts.mjs';
import {
  createInteractionCommand,
  toInteractionDto,
} from '../../lib/security/domains/interactions.mjs';
import {
  createTourCommand,
  updateTourCommand,
} from '../../lib/security/domains/tours.mjs';
import { listProjects } from '../../lib/security/domains/governance.mjs';
import {
  contactCreateSchema,
  interactionCreateSchema,
  tourCommandSchema,
  tourIdCommandSchema,
} from '../../lib/security/schemas.mjs';
import { SecurityError } from '../../lib/security/errors.mjs';

const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8');

const USER_A = '00000000-0000-4000-8000-000000000001';
const USER_B = '00000000-0000-4000-8000-000000000002';

function context(overrides = {}) {
  return {
    userId: USER_A,
    globalRole: null,
    aal: 2,
    memberships: [
      { projectId: 1, role: 'coord', status: 'active' },
      { projectId: 2, role: 'coord', status: 'active' },
    ],
    ...overrides,
  };
}

const contactInput = {
  projectId: 2,
  name: 'Synthetic Contact',
  phone: '050-0000000',
  city: 'Synthetic City',
  area: 'North',
  depth: 'friendly',
  profession: 'teacher',
  age: 42,
  gender: 'male',
  highPotential: true,
  daysSinceLastContact: 0,
  lastInteractionDate: '2026-08-29',
  nextAction: 'call',
  nextActionDate: '2026-09-01',
  source: 'external',
  joinedAt: '2026-08-29',
  notes: 'operational notes',
  howMet: 'event',
  mitzvot: { synthetic: 1 },
  mitzvotHistory: [{ mitzva: 'synthetic', from: 0, to: 1, date: '2026-08-29' }],
  isGraduate: false,
  referredBy: null,
  meetingPlaceCity: 'Synthetic City',
  meetingPlaceNumber: '12',
  meetingHouseCity: 'Synthetic City',
  meetingHouseNumber: '12',
  meetingHouseKey: '12_Synthetic City',
  tourId: 'tour-sheet-123',
};

test('I1 faithful CRM fixture uses the repository legacy ID and column contract', async () => {
  const sql = await read('tests/security/fixtures/legacy-security-schema.sql');
  const contacts = sql.match(/create table public\.contacts\s*\([\s\S]*?\n\);/i)?.[0] ?? '';
  const interactions = sql.match(/create table public\.interactions\s*\([\s\S]*?\n\);/i)?.[0] ?? '';
  const tours = sql.match(/create table public\.tours\s*\([\s\S]*?\n\);/i)?.[0] ?? '';

  assert.match(contacts, /id\s+bigint\s+generated by default as identity primary key/i);
  for (const column of [
    'is_active', 'area', 'depth', 'profession', 'age', 'gender', 'high_potential',
    'days_since_last_contact', 'last_interaction_date', 'next_action', 'next_action_date',
    'source', 'joined_at', 'how_met', 'mitzvot', 'mitzvot_history', 'is_graduate',
    'referred_by', 'meeting_place_city', 'meeting_place_number', 'tour_id',
    'meetingHouseCity', 'meetingHouseNumber', 'meetingHouseKey',
  ]) assert.match(contacts, new RegExp(`"?${column}"?\\s`, 'i'), `contacts.${column} missing`);
  assert.doesNotMatch(contacts, /\bstatus\b|\bnext_action_at\b/i);

  assert.match(interactions, /id\s+bigint\s+generated by default as identity primary key/i);
  assert.match(interactions, /contact_id\s+bigint/i);
  for (const column of [
    'date', 'time', 'duration_minutes', 'outcome', 'description', 'ai_summary',
    'next_action', 'next_action_date', 'notes', 'participants',
  ]) assert.match(interactions, new RegExp(`\\b${column}\\b`, 'i'), `interactions.${column} missing`);
  assert.doesNotMatch(interactions, /\boccurred_at\b/i);

  assert.match(tours, /id\s+text\s+primary key/i);
  assert.match(tours, /tour_number\s+text\s+not null/i);
  assert.match(tours, /settlement\s+text\s+not null/i);
  assert.doesNotMatch(tours, /\btitle\b/i);
});

test('I1 contact create requires explicit authorized project and preserves operational fields', async () => {
  assert.equal(contactCreateSchema.safeParse(contactInput).success, true);
  const command = await createContactCommand(context(), contactInput, {
    isActiveMember: async (projectId, userId) => projectId === 2 && userId === USER_B,
  });
  assert.equal(command.project_id, 2);
  assert.equal(command.assigned_user_id, USER_A);
  assert.deepEqual(command.mitzvot, { synthetic: 1 });
  assert.deepEqual(command.mitzvot_history, contactInput.mitzvotHistory);
  for (const column of [
    'area', 'depth', 'profession', 'age', 'gender', 'high_potential',
    'days_since_last_contact', 'last_interaction_date', 'next_action', 'next_action_date',
    'source', 'joined_at', 'how_met', 'is_graduate', 'referred_by',
    'meeting_place_city', 'meeting_place_number', 'meetingHouseCity',
    'meetingHouseNumber', 'meetingHouseKey', 'tour_id',
  ]) assert.equal(column in command, true, `${column} was dropped`);

  await assert.rejects(
    () => createContactCommand(context(), { ...contactInput, projectId: undefined }),
    (error) => error instanceof SecurityError && error.code === 'PROJECT_REQUIRED',
  );
  await assert.rejects(
    () => createContactCommand(context(), { ...contactInput, projectId: 3 }),
    (error) => error instanceof SecurityError && error.code === 'PROJECT_REQUIRED',
  );
});

test('I1 contact update preserves derived operational persistence fields', async () => {
  const existing = { id: 1001, project_id: 2, assigned_user_id: USER_A };
  const command = await updateContactCommand(context(), existing, {
    daysSinceLastContact: 3,
    lastInteractionDate: '2026-08-27',
    nextAction: 'follow up',
    nextActionDate: '2026-09-02',
    mitzvot: { synthetic: 2 },
    mitzvotHistory: [{ mitzva: 'synthetic', from: 1, to: 2, date: '2026-08-27' }],
  });
  assert.deepEqual(command, {
    days_since_last_contact: 3,
    last_interaction_date: '2026-08-27',
    next_action: 'follow up',
    next_action_date: '2026-09-02',
    mitzvot: { synthetic: 2 },
    mitzvot_history: [{ mitzva: 'synthetic', from: 1, to: 2, date: '2026-08-27' }],
  });
});

test('I1 interaction repository preserves payroll and operational fields without invented columns', async () => {
  const input = {
    contactId: 1001,
    date: '2026-08-29',
    time: '09:15',
    type: 'phone',
    quality: 'friendly',
    durationMinutes: 35,
    outcome: 'positive',
    notes: 'notes',
    description: 'description',
    aiSummary: 'summary',
    nextAction: 'follow up',
    nextActionDate: '2026-09-02',
    participants: { count: 2, clients: [{ id: 1002, name: 'Synthetic Participant' }], external: [] },
  };
  assert.equal(interactionCreateSchema.safeParse(input).success, true);
  const contact = { id: 1001, project_id: 1, assigned_user_id: USER_A };
  const command = await createInteractionCommand(context({ memberships: [
    { projectId: 1, role: 'activist', status: 'active' },
  ] }), contact, input);
  assert.deepEqual(command, {
    contact_id: 1001,
    actor_user_id: USER_A,
    project_id: 1,
    date: '2026-08-29',
    time: '09:15',
    type: 'phone',
    quality: 'friendly',
    duration_minutes: 35,
    outcome: 'positive',
    notes: 'notes',
    description: 'description',
    ai_summary: 'summary',
    next_action: 'follow up',
    next_action_date: '2026-09-02',
    participants: input.participants,
  });
  assert.equal('occurred_at' in command, false);

  const dto = toInteractionDto({ id: 9001, activist_id: 1101, ...command });
  assert.equal(dto.id, 9001);
  assert.equal(dto.activistCode, 1101);
  assert.equal(dto.durationMinutes, 35);
  assert.equal(dto.outcome, 'positive');
  assert.equal(dto.description, 'description');
  assert.equal(dto.aiSummary, 'summary');
  assert.equal(dto.nextAction, 'follow up');
  assert.equal(dto.nextActionDate, '2026-09-02');
});

test('I1 tour contract uses text IDs, tour_number mapping and required legacy fields', async () => {
  assert.equal(tourIdCommandSchema.safeParse({ tourId: 'tour-sheet-123' }).success, true);
  assert.equal(tourCommandSchema.safeParse({ title: 'Tour only' }).success, false);
  const ctx = context({ memberships: [{ projectId: 1, role: 'coord', status: 'active' }] });
  const created = await createTourCommand(ctx, { title: 'Tour 12', settlement: 'Synthetic' }, {
    createId: () => 'server-tour-id',
  });
  assert.equal(created.id, 'server-tour-id');
  assert.equal(created.tour_number, 'Tour 12');
  assert.equal(created.settlement, 'Synthetic');
  assert.equal(created.date, undefined);
  assert.equal(created.guide_name, undefined);
  const updated = await updateTourCommand(ctx, {
    id: 'tour-sheet-123', project_id: 1, status: 'upcoming', assigned_user_ids: [],
  }, { title: 'Renamed' });
  assert.deepEqual(updated, { tour_number: 'Renamed' });
});

test('I1 project listing does not query a nonexistent projects.is_active column', async () => {
  let eqCalls = 0;
  const query = {
    select() { return this; },
    eq() { eqCalls += 1; return this; },
    async order() { return { data: [], error: null }; },
  };
  await listProjects(context({ db: { from: () => query } }));
  assert.equal(eqCalls, 0);
});

test('I1 browser adapter installs server IDs and does not reuse UUID ownership as legacy code', async () => {
  const source = await read('lib/CrmStore.jsx');
  assert.match(source, /const\s+savedInteraction\s*=\s*insertResult\.data/);
  assert.match(source, /setInteractions\([\s\S]*savedInteraction/);
  assert.doesNotMatch(source, /interactionId:\s*interactionPayload\.id/);
  assert.match(source, /const\s+savedContact\s*=\s*insertResult\.data/);
  assert.doesNotMatch(source, /activist_id:\s*contact\.assignedUserId/);
});
