-- TEST-ONLY repository-derived legacy schema fixture.
-- This is not a production migration and must never be placed in the migration chain.
-- It is the repository-derived canonical pre-cutover CRM contract used to
-- exercise migrations 0018-0024 on a disposable local Supabase database.
-- Production remains authoritative and must still be inspected at G5.

create extension if not exists pgcrypto;

create table public.projects (
  id integer generated by default as identity primary key,
  name text not null,
  security_run_id uuid
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null,
  project_id integer references public.projects(id),
  project_ids integer[] not null default '{}',
  activist_code integer unique,
  security_run_id uuid
);

create table public.contacts (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id),
  activist_id integer,
  name text not null,
  phone text,
  city text,
  area text,
  depth text,
  profession text,
  age integer,
  gender text,
  is_active boolean not null default true,
  high_potential boolean not null default false,
  days_since_last_contact integer not null default 0,
  last_interaction_date date,
  next_action text,
  next_action_date date,
  source text,
  joined_at date,
  notes text,
  how_met text,
  mitzvot jsonb not null default '{}',
  mitzvot_history jsonb not null default '[]',
  is_graduate boolean not null default false,
  referred_by bigint references public.contacts(id),
  meeting_place_city text,
  meeting_place_number text,
  tour_id text,
  "meetingHouseCity" text,
  "meetingHouseNumber" text,
  "meetingHouseKey" text,
  security_run_id uuid
);

create table public.interactions (
  id bigint generated by default as identity primary key,
  contact_id bigint references public.contacts(id),
  project_id integer not null references public.projects(id),
  activist_id integer,
  type text not null,
  quality text,
  duration_minutes integer not null default 0,
  date date not null,
  time text,
  outcome text,
  notes text,
  description text,
  ai_summary text,
  next_action text,
  next_action_date date,
  participants jsonb not null default '{}',
  security_run_id uuid
);

create table public.base_meeting_reports (
  id uuid primary key default gen_random_uuid(),
  project_id integer not null references public.projects(id),
  activist_id integer,
  security_run_id uuid
);

create table public.meeting_houses (
  id text primary key,
  project_id integer not null references public.projects(id),
  assigned_activists integer[] not null default '{}',
  security_run_id uuid
);

create table public.meeting_reminders (
  id uuid primary key default gen_random_uuid(),
  meeting_id text not null,
  type text not null,
  coordinator_id text,
  activist_id text,
  remind_at timestamptz not null,
  security_run_id uuid
);

create table public.tours (
  id text primary key,
  project_id integer not null references public.projects(id),
  tour_number text not null,
  settlement text not null,
  date date,
  start_time text,
  guide_name text not null default '',
  guide_activist_id integer,
  host_activist_id integer,
  assigned_activists integer[] not null default '{}',
  status text not null default 'upcoming',
  notes text,
  report jsonb,
  reported_at timestamptz,
  security_run_id uuid
);

create table public.expenses (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id),
  activist_id integer,
  date date not null,
  amount numeric not null,
  description text,
  security_run_id uuid
);

create table public.bonus_cancellations (
  id uuid primary key default gen_random_uuid(),
  project_id integer not null references public.projects(id),
  activist_id integer,
  cancelled_by integer,
  bonus_key text not null,
  security_run_id uuid
);

create table public.payment_config (
  id integer primary key,
  rate_phone_friendly numeric not null default 0,
  rate_phone_torani numeric not null default 0,
  rate_video_friendly numeric not null default 0,
  rate_video_torani numeric not null default 0,
  rate_frontal_friendly numeric not null default 0,
  rate_frontal_torani numeric not null default 0,
  rate_multi numeric not null default 0,
  rate_shabbat_hosting numeric not null default 0,
  rate_tour_guide numeric not null default 0,
  min_duration_minutes integer not null default 0,
  cap_phone integer not null default 0,
  cap_frontal integer not null default 0,
  cap_multi integer not null default 0,
  cap_contact_phone_high integer not null default 0,
  cap_contact_phone_regular integer not null default 0,
  cap_contact_frontal_high integer not null default 0,
  cap_contact_frontal_regular integer not null default 0,
  bonus_loyalty_6 numeric not null default 0,
  bonus_loyalty_4 numeric not null default 0,
  bonus_mitzvot_level numeric not null default 0,
  bonus_new_participant numeric not null default 0,
  security_run_id uuid
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id text not null,
  client_id text unique,
  type text not null,
  title text not null,
  body text not null,
  url text,
  priority text,
  read boolean not null default false,
  created_at timestamptz not null default now(),
  security_run_id uuid
);

create table public.notification_reads (
  id uuid primary key default gen_random_uuid(),
  recipient_id text not null,
  notification_id uuid references public.notifications(id),
  read_at timestamptz not null default now(),
  security_run_id uuid
);

create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  activist_id text not null,
  subscription jsonb not null,
  security_run_id uuid
);

create table public.fcm_tokens (
  id uuid primary key default gen_random_uuid(),
  activist_id text not null,
  token text not null,
  security_run_id uuid
);

create table public.feedback_reports (
  id uuid primary key default gen_random_uuid(),
  project_id integer not null references public.projects(id),
  reporter_id integer,
  security_run_id uuid
);

create view public.activist_directory as
select id, name, role, project_id, activist_code
from public.profiles;
