-- 0007_expenses.sql — דיווחי הוצאות של פעילים (בלי קבלות, לפי החלטת נדב 2026-07-02).
-- להרצה ב-Supabase SQL Editor.
create table if not exists public.expenses (
  id          bigint generated by default as identity primary key,
  activist_id integer not null,
  project_id  integer,
  date        date not null default current_date,
  amount      numeric not null check (amount > 0),
  description text not null,
  created_at  timestamptz not null default now()
);

alter table public.expenses enable row level security;

-- מדיניות מתירנית ל-authenticated — תואם לדפוס הקיים של contacts/interactions
drop policy if exists "expenses_select_authenticated" on public.expenses;
create policy "expenses_select_authenticated" on public.expenses
  for select to authenticated using (true);

drop policy if exists "expenses_insert_authenticated" on public.expenses;
create policy "expenses_insert_authenticated" on public.expenses
  for insert to authenticated with check (true);

drop policy if exists "expenses_delete_authenticated" on public.expenses;
create policy "expenses_delete_authenticated" on public.expenses
  for delete to authenticated using (true);
