-- migrations/0014_bonus_cancellations.sql
--
-- מאפשר לרכז (ולתפקידים מעליו) לבטל בונוס שמגיע לפעיל (בונוס-מצוות/בונוס-חדש/בונוס-לימוד).
-- הבונוסים עצמם נגזרים (לא שורות עצמאיות ב-DB) — ראה lib/paymentCalc.js / lib/CrmStore.jsx.
-- לכן טבלה זו לא "מוחקת" בונוס, אלא שומרת סימון ביטול לפי מפתח יציב (bonus_key, ראה
-- makeBonusKey ב-lib/paymentCalc.js) — ומנוע התשלום מסנן לפיו לפני חישוב הסכום הכולל.
--
-- להרצה ב-Supabase SQL Editor. משתמש בפונקציות העזר app_current_role()/app_current_activist_code()/
-- app_current_project_ids() שהוגדרו ב-migrations/0013_activist_isolation_rls.sql.

create table if not exists public.bonus_cancellations (
  id            bigint generated by default as identity primary key,
  bonus_key     text not null unique,
  activist_id   integer not null,
  project_id    integer,
  "desc"        text,
  amount        numeric,
  cancelled_by  integer,
  created_at    timestamptz not null default now()
);

alter table public.bonus_cancellations enable row level security;

drop policy if exists "bonus_cancellations_select" on public.bonus_cancellations;
create policy "bonus_cancellations_select" on public.bonus_cancellations
  for select to authenticated using (
    app_current_role() = 'ceo'
    or activist_id = app_current_activist_code()
    or (app_current_role() in ('coord','head','finance') and project_id = any(app_current_project_ids()))
  );

-- ביטול בונוס: רכז/ראש-פרויקט/מנכ"ל בלבד (לא כספים — תפקיד צפייה בלבד כאן)
drop policy if exists "bonus_cancellations_insert" on public.bonus_cancellations;
create policy "bonus_cancellations_insert" on public.bonus_cancellations
  for insert to authenticated with check (
    app_current_role() = 'ceo'
    or (app_current_role() in ('coord','head') and project_id = any(app_current_project_ids()))
  );

-- שחזור בונוס שבוטל בטעות (מחיקת שורת הביטול) — אותם תפקידים
drop policy if exists "bonus_cancellations_delete" on public.bonus_cancellations;
create policy "bonus_cancellations_delete" on public.bonus_cancellations
  for delete to authenticated using (
    app_current_role() = 'ceo'
    or (app_current_role() in ('coord','head') and project_id = any(app_current_project_ids()))
  );
